apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  title: Backstage Mathod
  description: The Backstage instance running on backstage.mathod.fr
  annotations:
    github.com/project-slug: Mathod95/backstage
    # Docs live in docs/ with mkdocs.yml at the repo root
    backstage.io/techdocs-ref: dir:.
  tags:
    - backstage
spec:
  type: website
  owner: group:admins
  lifecycle: production
