site_name: Backstage Mathod
site_description: Documentation du Backstage de backstage.mathod.fr
repo_url: https://github.com/Mathod95/backstage
edit_uri: edit/main/docs
nav:
  - Backstage:
      - Personnalisation:
          - Où sont les réglages: backstage/personnalisation/reglages.md
          - Thème (MUI et BUI): backstage/personnalisation/theme.md
          - Page de connexion: backstage/personnalisation/page-de-connexion.md
  - Zensical:
      - Authoring: zensical/authoring.md
      - Configuration: zensical/configuration.md

plugins:
  - techdocs-core
