---
# Summary of the GitHub templates, listed in catalog/all.yaml.
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-location
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: templates-github
  description: GitHub templates
spec:
  targets:
    - ./github/create-repo/template.yaml
